###
POST http://localhost:5000/api/jobs/check-price
Content-Type: application/json

{
    "email": "davidkraku69@gmail.com",
    "url": "https://www.popmart.com/gb/products/1064/the-monsters-big-into-energy-series-vinyl-plush-pendant-blind-box"
}